apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
    spec:
      containers:
      - name: api-demo
        image: 306192109948.dkr.ecr.us-east-1.amazonaws.com/pocjlondonos:latest
        ports:
        - containerPort: 8080
